[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps = 
    marciot/ESP32CompositeColorVideo@^1.0.0

board_build.partitions = huge_app.csv
build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DBUFFER_SIZE=24000
